dataset_name: UKB
image_path: /data/cwang/remote/fmri/ukb_preprocessed
image_path_fc: /data/cwang/remote/fmri/ukb_preprocessed

pretrain_only: true

defaults:
  dataset_split_num: 1
  batch_size_override: 8
